echo "select voterId from voters where voterStatus = 'ACT' and precinct = 101" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct101_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 102" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct102_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 103" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct103_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 104" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct104_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 105" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct105_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 106" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct106_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 107" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct107_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 108" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct108_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 109" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct109_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 110" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct110_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 111" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct111_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 112" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct112_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 113" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct113_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 114" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct114_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 115" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct115_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 116" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct116_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 117" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct117_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 118" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct118_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 119" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct119_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 120" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct120_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 121" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct121_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 122" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct122_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 123" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct123_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 124" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct124_IDs.tx
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 125" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct125_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 126" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct126_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 127" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct127_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 128" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct128_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 129" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct129_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 130" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct130_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 131" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct131_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 132" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct132_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 133" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct133_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 134" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct134_IDs.txt
echo "select voterId from voters where voterStatus = 'ACT' and precinct = 135" | sqlite3 -noheader ~/Documents/src/python/votersdb2020 > ~/Documents/src/python/StPeteActiveVotersPrecinct135_IDs.txt

