PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE voters (
    voterId integer PRIMARY key,
    county TEXT NOT NULL,
    lastName TEXT NOT NULL,
    nameSuffix TEXT,
    firstName TEXT NOT NULL,
    middleName TEXT,
    pubRecExempt TEXT,
    resAddr1 TEXT NOT NULL,
    resAddr2 TEXT,
    resCity TEXT NOT NULL,
    resState TEXT NOT NULL,
    resZip TEXT NOT NULL,
    mailAddr1 TEXT,
    mailAddr2 TEXT 
    mailAddr3 TEXT,
    mailCity TEXT,
    mailState TEXT,
    mailZip TEXT,
    mailCountry TEXT,
    gender TEXT,
    race TEXT,
    birthDate DATE,
    regDate DATE,
    party TEXT,
    precinct TEXT,
    precinctGroup TEXT,
    precinctSplit TEXT,
    precinctSuffix TEXT,
    voterStatus TEXT,
    congDistrict TEXT,
    houseDistrict TEXT,
    senateDistrict TEXT,
    countyDistrict TEXT,
    schoolDistrict TEXT,
    daytimeAreacode TEXT,
    daytimePhone TEXT,
    daytimePhoneExt TEXT,
    emailAddress TEXT

);
INSERT INTO voters VALUES(10001001,'PIN','Smith',NULL,'James',NULL,NULL,'300 Main St.',NULL,'St Petersburg','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001002,'PIN','Jones',NULL,'Jennifer',NULL,NULL,'43l23 Gulf Blvd',NULL,'St Petersburg','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001003,'PIN','Adams',NULL,'Ashley',NULL,NULL,'6291 Bahia Way',NULL,'St Petersburg','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001004,'PIN','Rogers',NULL,'Peter',NULL,NULL,'13 Tartan Dr',NULL,'St Petersburg','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001005,'PIN','Baker',NULL,'Bubba',NULL,NULL,'1555 38th Ave. S.',NULL,'St Petersburg','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001006,'PIN','Troy',NULL,'Edith',NULL,NULL,'9322 Corey Ave',NULL,'St Pete Beach','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001007,'PIN','Osteen',NULL,'Frances',NULL,NULL,'14444 135th St',NULL,'Treasure Island','FL','33705',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO voters VALUES(10001008,'PIN','Dunne',NULL,'Irene',NULL,NULL,'200 46th Ave',NULL,'St Pete Beach','FL','33706',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
COMMIT;
